=== umesh1639/G7CaseStudy2/CaseStudy2/CaseStudy2/umesh/G7CaseStudy1-master/G7CaseStudy1-master/StaticAnalyzer/StaticAnalysisReports/CSharpMetricReport.dtd
<!ENTITY GreaterThanSign       "&#x0026;#x003E;">
<!ENTITY LessThanSign          "&#x0026;#x003C;">
<!ELEMENT MetricsReport (SystemSummary, FileMetricsList)>
<!ELEMENT FileMetricsList (FileMetrics)*>
<!ELEMENT FileMetrics (FileSummary, TypeMetricsList)>
<!ELEMENT TypeMetricsList (TypeMetrics)*>
<!ELEMENT TypeMetrics (TypeSummary, MethodMetricsList)>
<!ELEMENT MethodMetricsList (MethodMetrics)*>
<!ELEMENT SystemSummary (SourceLines,CSharpCodeLines,
                         CommentLines,Files,Types,
                         Methods,AggregateCyclomaticComplexity,MeanCyclomaticComplexity,MedianCyclomaticComplexity,Conditionals,
                         DecisionDensity,
                         MaxLoopDepth,MaxLoopDepthPosition?,
                         MaxConditionalDepth,MaxConditionalDepthPosition?,
                         HalsteadUniqueOperators,HalsteadUniqueOperands,
                         HalsteadOperatorOccurrence,HalsteadOperandOccurrence,
                         HalsteadProgramLength,HalsteadProgramVocabulary,
                         HalsteadProgramVolume,HalsteadProgramDifficulty,
                         HalsteadProgramEffort,HalsteadBugPrediction,
                         SEIMaintainabilityIndex)>
<!ELEMENT FileSummary (FileName,SourceLines,CSharpCodeLines,
                         CommentLines,Types,
                         Methods,AggregateCyclomaticComplexity,MeanCyclomaticComplexity,MedianCyclomaticComplexity,Conditionals,
                         DecisionDensity,
                         MaxLoopDepth,LineNumber?,
                         MaxConditionalDepth,LineNumber?,
                         HalsteadUniqueOperators,HalsteadUniqueOperands,
                         HalsteadOperatorOccurrence,HalsteadOperandOccurrence,
                         HalsteadProgramLength,HalsteadProgramVocabulary,
                         HalsteadProgramVolume,HalsteadProgramDifficulty,
                         HalsteadProgramEffort,HalsteadBugPrediction,
                         SEIMaintainabilityIndex)>
<!ELEMENT TypeSummary (TypeName,LineNumber,CSharpCodeLines,
                         CommentLines,
                         Methods,AggregateCyclomaticComplexity,MeanCyclomaticComplexity,MedianCyclomaticComplexity,Conditionals,
                         DecisionDensity,
                         MaxLoopDepth,LineNumber?,
                         MaxConditionalDepth,LineNumber?,
                         HalsteadUniqueOperators,HalsteadUniqueOperands,
                         HalsteadOperatorOccurrence,HalsteadOperandOccurrence,
                         HalsteadProgramLength,HalsteadProgramVocabulary,
                         HalsteadProgramVolume,HalsteadProgramDifficulty,
                         HalsteadProgramEffort,HalsteadBugPrediction,
                         SEIMaintainabilityIndex)>
<!ELEMENT MethodMetrics (MethodName,LineNumber,CSharpCodeLines,
                         CommentLines,
                        CyclomaticComplexity,Conditionals,
                         DecisionDensity,
                         MaxLoopDepth,LineNumber?,
                         MaxConditionalDepth,LineNumber?,
                         HalsteadUniqueOperators,HalsteadUniqueOperands,
                         HalsteadOperatorOccurrence,HalsteadOperandOccurrence,
                         HalsteadProgramLength,HalsteadProgramVocabulary,
                         HalsteadProgramVolume,HalsteadProgramDifficulty,
                         HalsteadProgramEffort,HalsteadBugPrediction,
                         SEIMaintainabilityIndex)>

<!ELEMENT FileName (#PCDATA)>
<!ELEMENT TypeName (#PCDATA)>
<!ELEMENT MethodName (#PCDATA)>
<!ELEMENT SourceLines (#PCDATA)>
<!ELEMENT CSharpCodeLines (#PCDATA)>
<!ELEMENT CommentLines (#PCDATA)>
<!ELEMENT Files (#PCDATA)>
<!ELEMENT Types (#PCDATA)>
<!ELEMENT Methods (#PCDATA)>
<!ELEMENT Conditionals (#PCDATA)>
<!ELEMENT CyclomaticComplexity (#PCDATA)>
<!ELEMENT AggregateCyclomaticComplexity (#PCDATA)>
<!ELEMENT MeanCyclomaticComplexity (#PCDATA)>
<!ELEMENT MedianCyclomaticComplexity (#PCDATA)>
<!ELEMENT DecisionDensity (#PCDATA)>
<!ELEMENT MaxLoopDepth (#PCDATA)>
<!ELEMENT MaxLoopDepthPosition (Position)>
<!ELEMENT MaxConditionalDepth (#PCDATA)>
<!ELEMENT MaxConditionalDepthPosition (Position)>
<!ELEMENT Position (FileName,PackageName,TypeName,LineNumber)>
<!ELEMENT PackageName (#PCDATA)>
<!ELEMENT LineNumber (#PCDATA)>                
<!ELEMENT HalsteadUniqueOperators (#PCDATA)>
<!ELEMENT HalsteadUniqueOperands (#PCDATA)>
<!ELEMENT HalsteadOperatorOccurrence (#PCDATA)>
<!ELEMENT HalsteadOperandOccurrence (#PCDATA)>
<!ELEMENT HalsteadProgramLength (#PCDATA)>
<!ELEMENT HalsteadProgramVocabulary (#PCDATA)>
<!ELEMENT HalsteadProgramVolume (#PCDATA)>
<!ELEMENT HalsteadProgramDifficulty (#PCDATA)>
<!ELEMENT HalsteadProgramEffort (#PCDATA)>
<!ELEMENT HalsteadBugPrediction (#PCDATA)>
<!ELEMENT SEIMaintainabilityIndex (#PCDATA)>

=== umesh1639/G7CaseStudy2/CaseStudy2/CaseStudy2/umesh/G7CaseStudy1-master/G7CaseStudy1-master/StaticAnalyzer/StaticAnalysisReports/2019_08/05_10_43/CSharpMetricReport.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE MetricsReport SYSTEM "C:\Users\320050767\Source\Repos\G7CaseStudy13\StaticAnalyzer\StaticAnalysisReports\CSharpMetricReport.dtd">
<MetricsReport>
<SystemSummary>
<SourceLines>878</SourceLines>
<CSharpCodeLines>733</CSharpCodeLines>
<CommentLines>49</CommentLines>
<Files>13</Files>
<Types>13</Types>
<Methods>54</Methods>
<AggregateCyclomaticComplexity>103</AggregateCyclomaticComplexity>
<MeanCyclomaticComplexity>1.91</MeanCyclomaticComplexity>
<MedianCyclomaticComplexity>1.00</MedianCyclomaticComplexity>
<Conditionals>51</Conditionals>
<DecisionDensity>2.08</DecisionDensity>
<MaxLoopDepth>2</MaxLoopDepth>
<MaxLoopDepthPosition><Position>
<FileName>C:/Users/320050767/Source/Repos/G7CaseStudy13/StaticAnalyzer/StaticAnalyzer/PluginWrappers/CSharpMetric/CSharpMetrics.cs</FileName>
<PackageName>%global_declaration_space%.StaticAnalyzer</PackageName>
<TypeName>CSharpMetrics</TypeName>
<LineNumber>104</LineNumber>
</Position>
</MaxLoopDepthPosition>
<MaxConditionalDepth>5</MaxConditionalDepth>
<MaxConditionalDepthPosition><Position>
<FileName>C:/Users/320050767/Source/Repos/G7CaseStudy13/StaticAnalyzer/StaticAnalyzer/PluginWrappers/NDeped/ParsingXmlNDepend.cs</FileName>
<PackageName>%global_declaration_space%.StaticAnalyzer</PackageName>
<TypeName>ParsingXmlNDepend</TypeName>
<LineNumber>23</LineNumber>
</Position>
</MaxConditionalDepthPosition>
<HalsteadUniqueOperators>192</HalsteadUniqueOperators>
<HalsteadUniqueOperands>723</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>1542</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>1561</HalsteadOperandOccurrence>
<HalsteadProgramLength>3103</HalsteadProgramLength>
<HalsteadProgramVocabulary>915</HalsteadProgramVocabulary>
<HalsteadProgramVolume>30526.16</HalsteadProgramVolume>
<HalsteadProgramDifficulty>207.27</HalsteadProgramDifficulty>
<HalsteadProgramEffort>6327148.21</HalsteadProgramEffort>
<HalsteadBugPrediction>10.18</HalsteadBugPrediction>
<SEIMaintainabilityIndex>113.36</SEIMaintainabilityIndex>
</SystemSummary>
<FileMetricsList>
<FileMetrics>
<FileSummary>
<FileName>C:/Users/320050767/Source/Repos/G7CaseStudy13/StaticAnalyzer/StaticAnalyzer/Configuration/Configuration.cs</FileName>
<SourceLines>52</SourceLines>
<CSharpCodeLines>30</CSharpCodeLines>
<CommentLines>8</CommentLines>
<Types>1</Types>
<Methods>3</Methods>
<AggregateCyclomaticComplexity>4</AggregateCyclomaticComplexity>
<MeanCyclomaticComplexity>1.33</MeanCyclomaticComplexity>
<MedianCyclomaticComplexity>1.00</MedianCyclomaticComplexity>
<Conditionals>1</Conditionals>
<DecisionDensity>0.18</DecisionDensity>
<MaxLoopDepth>1</MaxLoopDepth>
<LineNumber>30</LineNumber>
<MaxConditionalDepth>1</MaxConditionalDepth>
<LineNumber>30</LineNumber>
<HalsteadUniqueOperators>13</HalsteadUniqueOperators>
<HalsteadUniqueOperands>39</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>60</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>68</HalsteadOperandOccurrence>
<HalsteadProgramLength>128</HalsteadProgramLength>
<HalsteadProgramVocabulary>52</HalsteadProgramVocabulary>
<HalsteadProgramVolume>729.66</HalsteadProgramVolume>
<HalsteadProgramDifficulty>11.33</HalsteadProgramDifficulty>
<HalsteadProgramEffort>8269.44</HalsteadProgramEffort>
<HalsteadBugPrediction>0.24</HalsteadBugPrediction>
<SEIMaintainabilityIndex>141.69</SEIMaintainabilityIndex>
</FileSummary>
<TypeMetricsList>
<TypeMetrics>
<TypeSummary>
<TypeName>Configuration</TypeName>
<LineNumber>10</LineNumber>
<CSharpCodeLines>22</CSharpCodeLines>
<CommentLines>8</CommentLines>
<Methods>3</Methods>
<AggregateCyclomaticComplexity>4</AggregateCyclomaticComplexity>
<MeanCyclomaticComplexity>1.33</MeanCyclomaticComplexity>
<MedianCyclomaticComplexity>1.00</MedianCyclomaticComplexity>
<Conditionals>1</Conditionals>
<DecisionDensity>0.18</DecisionDensity>
<MaxLoopDepth>1</MaxLoopDepth>
<LineNumber>30</LineNumber>
<MaxConditionalDepth>1</MaxConditionalDepth>
<LineNumber>30</LineNumber>
<HalsteadUniqueOperators>11</HalsteadUniqueOperators>
<HalsteadUniqueOperands>22</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>38</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>45</HalsteadOperandOccurrence>
<HalsteadProgramLength>83</HalsteadProgramLength>
<HalsteadProgramVocabulary>33</HalsteadProgramVocabulary>
<HalsteadProgramVolume>418.68</HalsteadProgramVolume>
<HalsteadProgramDifficulty>11.25</HalsteadProgramDifficulty>
<HalsteadProgramEffort>4710.20</HalsteadProgramEffort>
<HalsteadBugPrediction>0.14</HalsteadBugPrediction>
<SEIMaintainabilityIndex>146.72</SEIMaintainabilityIndex>
</TypeSummary>
<MethodMetricsList>
<MethodMetrics>
<MethodName>Configurationconstructor</MethodName>
<LineNumber>18</LineNumber>
<CSharpCodeLines>4</CSharpCodeLines>
<CommentLines>0</CommentLines>
<CyclomaticComplexity>1</CyclomaticComplexity>
<Conditionals>0</Conditionals>
<DecisionDensity>0.25</DecisionDensity>
<MaxLoopDepth>0</MaxLoopDepth>
<MaxConditionalDepth>0</MaxConditionalDepth>
<HalsteadUniqueOperators>4</HalsteadUniqueOperators>
<HalsteadUniqueOperands>5</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>4</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>6</HalsteadOperandOccurrence>
<HalsteadProgramLength>10</HalsteadProgramLength>
<HalsteadProgramVocabulary>9</HalsteadProgramVocabulary>
<HalsteadProgramVolume>31.70</HalsteadProgramVolume>
<HalsteadProgramDifficulty>2.40</HalsteadProgramDifficulty>
<HalsteadProgramEffort>76.08</HalsteadProgramEffort>
<HalsteadBugPrediction>0.01</HalsteadBugPrediction>
<SEIMaintainabilityIndex>130.34</SEIMaintainabilityIndex>
</MethodMetrics>
<MethodMetrics>
<MethodName>Configurations</MethodName>
<LineNumber>15</LineNumber>
<CSharpCodeLines>1</CSharpCodeLines>
<CommentLines>0</CommentLines>
<CyclomaticComplexity>1</CyclomaticComplexity>
<Conditionals>0</Conditionals>
<DecisionDensity>1.00</DecisionDensity>
<MaxLoopDepth>0</MaxLoopDepth>
<MaxConditionalDepth>0</MaxConditionalDepth>
<HalsteadUniqueOperators>2</HalsteadUniqueOperators>
<HalsteadUniqueOperands>5</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>2</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>6</HalsteadOperandOccurrence>
<HalsteadProgramLength>8</HalsteadProgramLength>
<HalsteadProgramVocabulary>7</HalsteadProgramVocabulary>
<HalsteadProgramVolume>22.46</HalsteadProgramVolume>
<HalsteadProgramDifficulty>1.20</HalsteadProgramDifficulty>
<HalsteadProgramEffort>26.95</HalsteadProgramEffort>
<HalsteadBugPrediction>0.01</HalsteadBugPrediction>
<SEIMaintainabilityIndex>154.59</SEIMaintainabilityIndex>
</MethodMetrics>
<MethodMetrics>
<MethodName>LoadConfiguration</MethodName>
<LineNumber>24</LineNumber>
<CSharpCodeLines>11</CSharpCodeLines>
<CommentLines>6</CommentLines>
<CyclomaticComplexity>2</CyclomaticComplexity>
<Conditionals>1</Conditionals>
<DecisionDensity>0.18</DecisionDensity>
<MaxLoopDepth>1</MaxLoopDepth>
<LineNumber>30</LineNumber>
<MaxConditionalDepth>1</MaxConditionalDepth>
<LineNumber>30</LineNumber>
<HalsteadUniqueOperators>8</HalsteadUniqueOperators>
<HalsteadUniqueOperands>14</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>23</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>19</HalsteadOperandOccurrence>
<HalsteadProgramLength>42</HalsteadProgramLength>
<HalsteadProgramVocabulary>22</HalsteadProgramVocabulary>
<HalsteadProgramVolume>187.30</HalsteadProgramVolume>
<HalsteadProgramDifficulty>5.43</HalsteadProgramDifficulty>
<HalsteadProgramEffort>1016.75</HalsteadProgramEffort>
<HalsteadBugPrediction>0.06</HalsteadBugPrediction>
<SEIMaintainabilityIndex>149.10</SEIMaintainabilityIndex>
</MethodMetrics>
</MethodMetricsList>
</TypeMetrics>
</TypeMetricsList>
</FileMetrics>
<FileMetrics>
<FileSummary>
<FileName>C:/Users/320050767/Source/Repos/G7CaseStudy13/StaticAnalyzer/StaticAnalyzer/Configuration/ToolMeta.cs</FileName>
<SourceLines>36</SourceLines>
<CSharpCodeLines>30</CSharpCodeLines>
<CommentLines>0</CommentLines>
<Types>2</Types>
<Methods>7</Methods>
<AggregateCyclomaticComplexity>7</AggregateCyclomaticComplexity>
<MeanCyclomaticComplexity>1.00</MeanCyclomaticComplexity>
<MedianCyclomaticComplexity>1.00</MedianCyclomaticComplexity>
<Conditionals>0</Conditionals>
<DecisionDensity>0.45</DecisionDensity>
<MaxLoopDepth>0</MaxLoopDepth>
<MaxConditionalDepth>0</MaxConditionalDepth>
<HalsteadUniqueOperators>10</HalsteadUniqueOperators>
<HalsteadUniqueOperands>29</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>55</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>62</HalsteadOperandOccurrence>
<HalsteadProgramLength>117</HalsteadProgramLength>
<HalsteadProgramVocabulary>39</HalsteadProgramVocabulary>
<HalsteadProgramVolume>618.39</HalsteadProgramVolume>
<HalsteadProgramDifficulty>10.69</HalsteadProgramDifficulty>
<HalsteadProgramEffort>6610.40</HalsteadProgramEffort>
<HalsteadBugPrediction>0.21</HalsteadBugPrediction>
<SEIMaintainabilityIndex>129.17</SEIMaintainabilityIndex>
</FileSummary>
<TypeMetricsList>
<TypeMetrics>
<TypeSummary>
<TypeName>ToolMeta</TypeName>
<LineNumber>9</LineNumber>
<CSharpCodeLines>23</CSharpCodeLines>
<CommentLines>0</CommentLines>
<Methods>4</Methods>
<AggregateCyclomaticComplexity>4</AggregateCyclomaticComplexity>
<MeanCyclomaticComplexity>1.00</MeanCyclomaticComplexity>
<MedianCyclomaticComplexity>1.00</MedianCyclomaticComplexity>
<Conditionals>0</Conditionals>
<DecisionDensity>0.17</DecisionDensity>
<MaxLoopDepth>0</MaxLoopDepth>
<MaxConditionalDepth>0</MaxConditionalDepth>
<HalsteadUniqueOperators>7</HalsteadUniqueOperators>
<HalsteadUniqueOperands>10</HalsteadUniqueOperands>
<HalsteadOperatorOccurrence>37</HalsteadOperatorOccurrence>
<HalsteadOperandOccurrence>44</HalsteadOperandOccurrence>
<HalsteadProgramLength>81</HalsteadProgramLength>
<HalsteadProgramVocabulary>17</HalsteadProgramVocabulary>
<HalsteadProgramVolume>331.08</HalsteadProgramVolume>
<HalsteadProgramDifficulty>15.40</HalsteadProgramDifficulty>
<HalsteadProgramEffort>5098.70</HalsteadProgramEffort>
<HalsteadBugPrediction>0.11</HalsteadBugPrediction>
